# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    # def __init__(self, MainWindow):
    #     super(Ui_MainWindow, self).__init__()
    #     self.MainWindow = MainWindow
    #     self.setupUi(MainWindow)
    #     # MainWindow.show()


    def setupUi(self,MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(320, 290, 201, 71))
        self.Button1.setObjectName("Button1")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(140, 400, 551, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(630, 110, 161, 51))
        self.pushButton_1.setObjectName("pushButton_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 120, 181, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 221, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 190, 161, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 30, 301, 31))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionclasses = QtWidgets.QAction(MainWindow)
        self.actionclasses.setObjectName("actionclasses")
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # MainWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button1.setStatusTip(_translate("MainWindow", "Training the model with new data!"))
        self.Button1.setText(_translate("MainWindow", "Train"))
        self.progressBar.setStatusTip(_translate("MainWindow", "Progress Bar - wait for 100%"))
        self.pushButton_1.setStatusTip(_translate("MainWindow", "Upload class 0 here!"))
        self.pushButton_1.setText(_translate("MainWindow", "Upload"))
        self.label.setText(_translate("MainWindow", "Upload your faulty images here: "))
        self.label_2.setText(_translate("MainWindow", "Upload your clean/non-faulty images here: "))
        self.pushButton_2.setStatusTip(_translate("MainWindow", "Upload class 1 here!"))
        self.pushButton_2.setText(_translate("MainWindow", "Upload"))
        self.label_3.setText(_translate("MainWindow", "Categorial Detection - Faulty or non-faulty metal components"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionclasses.setText(_translate("MainWindow", "classes"))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
